Random stuff
anatom3000/GuessWhatWillHappenInThis pull request #87
Opened 2021-10-08 15:31 UTC by JFronny

Use LibJF resource events for sound replacing and early init, generate ores completely randomly using italian words, update gradle wrapper.\
Also generates a random codename based on the version number.

2021-10-08 16:06 UTC, MattiDragon commented on src/main/java/fr/anatom3000/gwwhit/util/ItalianUtil.java
> +package fr.anatom3000.gwwhit.util;
I don't static finals should be in SCREAMING_SNAKE_CASE even if they are private

2021-10-08 16:08 UTC, ENDERZOMBI102 requested changes
plz fix or undo

2021-10-09 23:34 UTC, ENDERZOMBI102 commented
i’ll merge it tomorrow then, in case some bug is found you’ll still have the time to fix it

2021-10-10 12:58 UTC, JFronny commented
![block_of_videotelefonia](https://user-images.githubusercontent.com/33260128/136696710-3d36e088-d58e-4d5e-96a2-64bbb627d3f3.png)

2021-10-12 15:03 UTC, merged